Repository urjimyu/My-Name, pull requests merged in 2025-03, with the labels that each got.

#11 [Feature/#3] : jimin 소개 페이지
  src/img/min_photo.jfif
  src/min/.gitkeep
  src/min/index.html
  src/min/min.css
Labels: feature, 지민 🐰

#9 [Feature/#2] : seonhui의 자기소개 기능 추가
  src/hui/img/kim.jpg
  src/hui/index.html
  src/hui/reset.css
  src/hui/style.css
Labels: feature, 선희 🐸

#12 [Feature/#4] : seonhui의 취미 소개 기능 추가
  src/hui/img/1.jpg
  src/hui/img/2.jpg
  src/hui/img/3.jpg
  src/hui/img/5.jpg
  src/hui/index.html
  src/hui/style.css
Labels: feature, 선희 🐸

#18 [Feature/#6] : hui trip의 추천 여행지 기능 추가
  src/hui/img/back.jpg
  src/hui/index.html
  src/hui/style.css
Labels: feature, 선희 🐸

#19 [Feature/#17] : 리팩토링합니다.
  src/hyun/hyun.css
  src/hyun/hyun_profile.html
  src/hyun/reset.css
Labels: refactor, 소현 🐣

#21 feat: gallery page
  src/img/gallery01.jfif
  src/img/gallery02.jfif
  src/img/gallery03.jfif
  src/img/gallery04.jfif
  src/img/gallery05.jfif
  src/img/gallery06.jfif
  src/min/index.html
  src/min/min.css
Labels: feature, 지민 🐰
